### ISSUE TITLE
build with crossbuilder

### ISSUE THREAD

**Issue by lduboeuf** [ubports/address-book-service#10]
I had no luck with using crossbuilder, installed dh-translations as usual but lots of package broken:

> Unpacking address-book-service-cross-build-deps:armhf (1.0) ...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Correcting dependencies...Starting pkgProblemResolver with broken count: 7
> Starting 2 pkgProblemResolver with broken count: 7
> Investigating (0) libebook-contacts-1.2-2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken libebook-contacts-1.2-2:armhf Depends on libedataserver-1.2-21 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.17)
>   Considering libedataserver-1.2-21:armhf 0 as a solution to libebook-contacts-1.2-2:armhf 10
>   Holding Back libebook-contacts-1.2-2:armhf rather than change libedataserver-1.2-21:armhf
> Investigating (0) gir1.2-edataserver-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken gir1.2-edataserver-1.2:armhf Depends on libedataserver-1.2-21 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.18.0)
>   Considering libedataserver-1.2-21:armhf 0 as a solution to gir1.2-edataserver-1.2:armhf 7
>   Holding Back gir1.2-edataserver-1.2:armhf rather than change libedataserver-1.2-21:armhf
> Investigating (0) libedataserver1.2-dev [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libdevel )
> Broken libedataserver1.2-dev:armhf Depends on libedataserver-1.2-21 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering libedataserver-1.2-21:armhf 0 as a solution to libedataserver1.2-dev:armhf 4
>   Holding Back libedataserver1.2-dev:armhf rather than change libedataserver-1.2-21:armhf
> Investigating (0) libedata-book-1.2-25 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken libedata-book-1.2-25:armhf Depends on libebook-contacts-1.2-2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.16.2)
>   Considering libebook-contacts-1.2-2:armhf 10 as a solution to libedata-book-1.2-25:armhf 3
>   Holding Back libedata-book-1.2-25:armhf rather than change libebook-contacts-1.2-2:armhf
> Investigating (0) libebook-1.2-16 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken libebook-1.2-16:armhf Depends on libebook-contacts-1.2-2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.16.2)
>   Considering libebook-contacts-1.2-2:armhf 10 as a solution to libebook-1.2-16:armhf 3
>   Holding Back libebook-1.2-16:armhf rather than change libebook-contacts-1.2-2:armhf
> Investigating (0) libebackend-1.2-10 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken libebackend-1.2-10:armhf Depends on libedataserver-1.2-21 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.17.90)
>   Considering libedataserver-1.2-21:armhf 0 as a solution to libebackend-1.2-10:armhf 2
>   Holding Back libebackend-1.2-10:armhf rather than change libedataserver-1.2-21:armhf
> Investigating (0) libfolks-eds25 [ armhf ] < none -> 0.11.1-2build2 > ( universe/libs )
> Broken libfolks-eds25:armhf Depends on libebook-1.2-16 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (>= 3.17)
>   Considering libebook-1.2-16:armhf 3 as a solution to libfolks-eds25:armhf 2
>   Holding Back libfolks-eds25:armhf rather than change libebook-1.2-16:armhf
> Investigating (0) libebook-contacts1.2-dev [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libdevel )
> Broken libebook-contacts1.2-dev:armhf Depends on libebook-contacts-1.2-2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering libebook-contacts-1.2-2:armhf 10 as a solution to libebook-contacts1.2-dev:armhf 1
>   Holding Back libebook-contacts1.2-dev:armhf rather than change libebook-contacts-1.2-2:armhf
> Investigating (0) gir1.2-folks-0.6 [ armhf ] < none -> 0.11.1-2build2 > ( universe/libs )
> Broken gir1.2-folks-0.6:armhf Depends on gir1.2-edataserver-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
>   Considering gir1.2-edataserver-1.2:armhf 7 as a solution to gir1.2-folks-0.6:armhf 1
>   Holding Back gir1.2-folks-0.6:armhf rather than change gir1.2-edataserver-1.2:armhf
> Investigating (0) libfolks-dev [ armhf ] < none -> 0.11.1-2build2 > ( universe/libdevel )
> Broken libfolks-dev:armhf Depends on gir1.2-folks-0.6 [ armhf ] < none -> 0.11.1-2build2 > ( universe/libs ) (= 0.11.1-2build2)
>   Considering gir1.2-folks-0.6:armhf 1 as a solution to libfolks-dev:armhf 1
>   Holding Back libfolks-dev:armhf rather than change gir1.2-folks-0.6:armhf
> Investigating (0) gir1.2-ebookcontacts-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( introspection )
> Broken gir1.2-ebookcontacts-1.2:armhf Depends on gir1.2-edataserver-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering gir1.2-edataserver-1.2:armhf 7 as a solution to gir1.2-ebookcontacts-1.2:armhf 1
>   Holding Back gir1.2-ebookcontacts-1.2:armhf rather than change gir1.2-edataserver-1.2:armhf
> Investigating (0) gir1.2-ebook-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs )
> Broken gir1.2-ebook-1.2:armhf Depends on gir1.2-ebookcontacts-1.2 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( introspection ) (= 3.18.5-1ubuntu1.2)
>   Considering gir1.2-ebookcontacts-1.2:armhf 1 as a solution to gir1.2-ebook-1.2:armhf 0
>   Holding Back gir1.2-ebook-1.2:armhf rather than change gir1.2-ebookcontacts-1.2:armhf
> Investigating (0) libebackend1.2-dev [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libdevel )
> Broken libebackend1.2-dev:armhf Depends on libebackend-1.2-10 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering libebackend-1.2-10:armhf 2 as a solution to libebackend1.2-dev:armhf 0
>   Holding Back libebackend1.2-dev:armhf rather than change libebackend-1.2-10:armhf
> Investigating (0) libfolks-eds-dev [ armhf ] < none -> 0.11.1-2build2 > ( universe/libdevel )
> Broken libfolks-eds-dev:armhf Depends on libfolks-eds25 [ armhf ] < none -> 0.11.1-2build2 > ( universe/libs ) (= 0.11.1-2build2)
>   Considering libfolks-eds25:armhf 2 as a solution to libfolks-eds-dev:armhf 0
>   Holding Back libfolks-eds-dev:armhf rather than change libfolks-eds25:armhf
> Investigating (0) libebook1.2-dev [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libdevel )
> Broken libebook1.2-dev:armhf Depends on libebook-1.2-16 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering libebook-1.2-16:armhf 3 as a solution to libebook1.2-dev:armhf 0
>   Holding Back libebook1.2-dev:armhf rather than change libebook-1.2-16:armhf
> Investigating (0) libedata-book1.2-dev [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libdevel )
> Broken libedata-book1.2-dev:armhf Depends on libedata-book-1.2-25 [ armhf ] < none -> 3.18.5-1ubuntu1.2 > ( libs ) (= 3.18.5-1ubuntu1.2)
>   Considering libedata-book-1.2-25:armhf 3 as a solution to libedata-book1.2-dev:armhf 0
>   Holding Back libedata-book1.2-dev:armhf rather than change libedata-book-1.2-25:armhf
> Investigating (0) address-book-service-cross-build-deps [ armhf ] < 1.0 > ( devel )
> Broken address-book-service-cross-build-deps:armhf Depends on libfolks-dev [ armhf ] < none -> 0.11.1-2build2 > ( universe/libdevel )
>   Considering libfolks-dev:armhf 1 as a solution to address-book-service-cross-build-deps:armhf -2
>   Removing address-book-service-cross-build-deps:armhf rather than change libfolks-dev:armhf
> Done

`

**Comment by lduboeuf** [comment]
So as i've tested successfully PR#12 with crossbuilder, i don't remember what i did to get it working or if crossbuilder was updated
I close it for now

**Comment by lduboeuf** [comment]
I reopen that issue since, i remember, i did test by fetching artifacts from CI and was not able to build it with crossbuilder

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-service/-/issues/1
